# Generated by Django 3.1.2 on 2021-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='http://bit.ly/3Cvjweh', max_length=1500),
        ),
    ]
